### ISSUE TITLE
Question: can delimiters be quoted?

### ISSUE THREAD

**Issue by thorstenhuhn** [daidokoro/qaz#35]
I recently needed to add an AWS SSM Document to one of my CloudFormation Stacks managed by Qaz. Due to the use of the Jinja-style for variable syntax "{{ _variable_ }}" in SSM documents as well I now get Gen-Time errors "function _variable_ not defined". I know I could change the qaz delimiters by setting a different `gen_time` value in `config.yml` but this would lead to different settings in different projects which might confuse my collegues also working on my templates.

My first idea to workaround this was to implement a function rendering a "string" to "{{ string }}" at Gen-time but I would prefer using quotes if possible.

Does anyone know a better way to address this issue?

**Comment by daidokoro** [comment]
Hey @thorstenhuhn 

You can definitely quote delimiters by using what I call double wrapping.. For example, 
say I want __{{ variable }}__ to be represented literally in my config file. I would do the following.

```go
{{ "{{ variable }}" }}
``` 
This would literally evaluate to __{{ variable }}__ when run.

If I wanted to keep the quotes I could do:

```
{{ `"{{ variable }}"` }}
```

Which would evaluate to: __"{{ value }}"__

**Comment by thorstenhuhn** [comment]
That's awesome, thanks a lot!
